### ISSUE TITLE
SyntaxError: Unexpected token 'with' in the latest version

### ISSUE THREAD

**Issue by sanzeeb3** [ryanhex53/gpt-po#18]
This used to work fine. but we're getting this error now:

```
file:///C:/laragon/www/dev/wp-content/plugins/aawp/node_modules/gpt-po/lib/src/index.js:5
import pkg from "../package.json" with { type: "json" };
                                  ^^^^

SyntaxError: Unexpected token 'with'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at async link (internal/modules/esm/module_job.js:47:21)
```

**Comment by ouyangem** [comment]
Apologies; in release 1.1.2, Node.js ought to be at version 18.x or higher.

**Comment by ryanhex53** [comment]
In release 1.1.2, Node.js ought to be at version 18.x or higher.
